name: "CI workflow demo at PUCIT"

on:
   pull_request:
       branches:
           - staging
jobs:
    test:
       runs-on: ubuntu-latest
       name: "Test"
       env:
          PORT: 5001
       steps:
          - name: "checkout"
            uses: actions/checkout@v3

          - name: "install dep"
            run: npm ci

          - name: "test"
            run: npm test

          - name: "build"
            run: | 

              echo "running npm build"
              npm run build --if-present
